--CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE CLINICA_REUMATOLOGIA;
GO

--USAR LA BASE DE DATOS CREADA
USE CLINICA_REUMATOLOGIA;
GO

--CREAR LAS TABLAS DE LA BASE DE DATOS

--TABLA ROL
CREATE TABLE ROL(
	ID_ROL INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ROL VARCHAR(50)
);

--TABLA USUARIOS
CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	ID_ROL INT,
	NOMBRE VARCHAR(100),
	PRIMER_APELLIDO VARCHAR(100),
	SEGUNDO_APELLIDO VARCHAR(100),
	CORREO_ELECTRONICO VARCHAR(100),
	NOMBRE_USUARIO VARCHAR(100),
	TELEFONO VARCHAR(50),
	CONTRASENA VARCHAR(100)
);

--TABLA CITA
CREATE TABLE CITA(
	ID_CITA INT IDENTITY(1,1) PRIMARY KEY,
	CEDULA_PACIENTE VARCHAR(50),
	ID_USUARIO INT,
	FECHA DATE,
	HORA TIME,
	MOTIVO VARCHAR(255)
);

--TABLA PACIENTE
CREATE TABLE PACIENTE(
	CEDULA_PACIENTE VARCHAR(50) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	PRIMER_APELLIDO VARCHAR(100),
	SEGUNDO_APELLIDO VARCHAR(100),
	EDAD INT,
	ID_SEXO INT,
	ID_OCUPACION INT,
	ID_DIRECCION INT,
	FECHA_NACIMIENTO INT
);

--TABLA SEXO
CREATE TABLE SEXO(
	ID_SEXO INT IDENTITY(1,1) PRIMARY KEY,
	SEXO VARCHAR(20)
);

--TABLA OCUPACION
CREATE TABLE OCUPACION(
	ID_OCUPACION INT IDENTITY(1,1) PRIMARY KEY,
	OCUPACION VARCHAR(20)
);

--TABLA DIRECCION
CREATE TABLE DIRECCION(
	ID_DIRECCION INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROVINCIA INT,
	ID_CANTON INT,
	ID_DISTRITO INT,
	DIRECCION VARCHAR(200)
);

--TABLA PROVINCIA
CREATE TABLE PROVINCIA(
	ID_PROVINCIA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PROVINCIA VARCHAR(100)
);
--TABLA CANTON
CREATE TABLE CANTON(
	ID_CANTON INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROVINCIA INT,
	NOMBRE_PROVINCIA VARCHAR(100)
);

--TABLA DISTRITO
CREATE TABLE DISTRITO(
	ID_DISTRITO INT IDENTITY(1,1) PRIMARY KEY,
	ID_CANTON INT,
	NOMBRE_DISTRITO VARCHAR(100)
);

CREATE TABLE EXPEDIENTE(
	ID_EXPEDIENTE INT IDENTITY(1,1) PRIMARY KEY,
	CEDULA_PACIENTE VARCHAR(50),
	ID_ANTECEDENTES INT,
	PADECIMIENTO_ACTUAL VARCHAR(2000),
	EXAMEN_FISICO VARCHAR(2000),
	IMPRESION_DIAGNOSTICA VARCHAR(2000),
	PLAN_TRATAMIENTO VARCHAR(2000)
);

CREATE TABLE ANTECEDENTES(
	ID_ANTECEDENTES INT IDENTITY(1,1) PRIMARY KEY,
	AGO VARCHAR(2000),
	APnoP VARCHAR(2000),
	APP VARCHAR(2000),
	AHF VARCHAR(2000),
	AQTx VARCHAR(2000)
);

CREATE TABLE BITACORA(
	ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
	ID_EXPEDIENTE INT,
	SINTOMATOLOGIA VARCHAR(2000),
	EVOLUCION VARCHAR(2000),
	CAMBIOS_TRATAMIENTO VARCHAR(2000)
);
GO


--LLAVES FORANEAS

--TABLA USUARIO
--REFERENCIA A LA TABLA ROL
ALTER TABLE USUARIO 
ADD CONSTRAINT FK_USUARIO_ROL
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA CITA
--REFERENCIA A LA TABLA USUARIO
ALTER TABLE CITA 
ADD CONSTRAINT FK_CITA_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A LA TABLA PACIENTE
ALTER TABLE CITA 
ADD CONSTRAINT FK_CITA_PACIENTE
FOREIGN KEY (CEDULA_PACIENTE) REFERENCES PACIENTE(CEDULA_PACIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA PACIENTE
--REFERENCIA A LA TABLA SEXO
ALTER TABLE PACIENTE 
ADD CONSTRAINT FK_PACIENTE_SEXO
FOREIGN KEY(ID_SEXO) REFERENCES SEXO(ID_SEXO)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA OCUPACION
ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_OCUPACION
FOREIGN KEY (ID_OCUPACION) REFERENCES OCUPACION(ID_OCUPACION)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA DIRECCION
ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_DIRECCION
FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA DIRECCION
--REFERENCIA A TABLA PROVINCIA
ALTER TABLE DIRECCION
ADD CONSTRAINT FK_DIRECCION_PROVINCIA
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA CANTON
ALTER TABLE DIRECCION
ADD CONSTRAINT FK_DIRECCION_CANTON
FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA DISTRITO
ALTER TABLE DIRECCION
ADD CONSTRAINT FK_DIRECCION_DISTRITO
FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA CANTÓN
--REFERENCIA A LA TABLA PROVINCIA
ALTER TABLE CANTON
ADD CONSTRAINT FK_CANTON_PROVINCIA
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

--TABLA DISTRITO
--REFERENCIA A LA TABLA CANTON
ALTER TABLE DISTRITO
ADD CONSTRAINT FK_DISTRITO_CANTON
FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

--TABLA EXPEDIENTE
--REFERENCIA A TABLA PACIENTE
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_PACIENTE
FOREIGN KEY (CEDULA_PACIENTE) REFERENCES PACIENTE(CEDULA_PACIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;


--REFERENCIA A TABLA ANTECEDENTES
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_ANTECEDENTES
FOREIGN KEY (ID_ANTECEDENTES) REFERENCES ANTECEDENTES (ID_ANTECEDENTES)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA BITACORA
--REFERENCIA A TABLA BITACORA
ALTER TABLE BITACORA
ADD CONSTRAINT FK_BITACORA_EXPEDIENTE
FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;






