--CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE CLINICA_REUMATOLOGIA;
GO

--USAR LA BASE DE DATOS CREADA
USE CLINICA_REUMATOLOGIA;
GO

--CREAR LAS TABLAS DE LA BASE DE DATOS

--TABLA ROL
CREATE TABLE ROL(
	ID_ROL INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ROL VARCHAR(50)
);
-- Insertar roles en la tabla ROL
INSERT INTO ROL (NOMBRE_ROL) VALUES ('Administrador');
INSERT INTO ROL (NOMBRE_ROL) VALUES ('Medico');
INSERT INTO ROL (NOMBRE_ROL) VALUES ('Secretario');
INSERT INTO ROL (NOMBRE_ROL) VALUES ('Paciente');

GO 

--TABLA USUARIOS
CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	ID_ROL INT,
	NOMBRE VARCHAR(100),
	PRIMER_APELLIDO VARCHAR(100),
	SEGUNDO_APELLIDO VARCHAR(100),
	CORREO_ELECTRONICO VARCHAR(100),
	NOMBRE_USUARIO VARCHAR(100),
	TELEFONO VARCHAR(50),
	CONTRASENA VARCHAR(100)
);

--TABLA CITA
CREATE TABLE CITA(
	ID_CITA INT IDENTITY(1,1) PRIMARY KEY,
	CEDULA_PACIENTE VARCHAR(50),
	ID_USUARIO INT,
	FECHA DATE,
	HORA TIME,
	MOTIVO VARCHAR(255)
);

--TABLA PACIENTE
CREATE TABLE PACIENTE(
	CEDULA_PACIENTE VARCHAR(50) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	PRIMER_APELLIDO VARCHAR(100),
	SEGUNDO_APELLIDO VARCHAR(100),
	EDAD INT,
	ID_SEXO INT,
	ID_OCUPACION INT,
	ID_DIRECCION INT,
	FECHA_NACIMIENTO DATE
);

--TABLA SEXO
CREATE TABLE SEXO(
	ID_SEXO INT IDENTITY(1,1) PRIMARY KEY,
	SEXO VARCHAR(20)
);

--TABLA OCUPACION
CREATE TABLE OCUPACION(
	ID_OCUPACION INT IDENTITY(1,1) PRIMARY KEY,
	OCUPACION VARCHAR(20)
);

--TABLA DIRECCION
CREATE TABLE DIRECCION(
	ID_DIRECCION INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROVINCIA INT,
	ID_CANTON INT,
	DIRECCION VARCHAR(200)
);

--TABLA PROVINCIA
CREATE TABLE PROVINCIA(
	ID_PROVINCIA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PROVINCIA VARCHAR(100)
);
--TABLA CANTON
CREATE TABLE CANTON(
	ID_CANTON INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROVINCIA INT,
	NOMBRE_PROVINCIA VARCHAR(100)
);

--TABLA EXPEDIENTE
CREATE TABLE EXPEDIENTE(
	ID_EXPEDIENTE INT IDENTITY(1,1) PRIMARY KEY,
	CEDULA_PACIENTE VARCHAR(50),
	ID_ANTECEDENTES INT,
);

CREATE TABLE ANTECEDENTES(
	ID_ANTECEDENTES INT IDENTITY(1,1) PRIMARY KEY,
	AGO VARCHAR(2000),
	APnoP VARCHAR(2000),
	APP VARCHAR(2000),
	AHF VARCHAR(2000),
	AQTx VARCHAR(2000)
);

CREATE TABLE BITACORA(
	ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
	ID_EXPEDIENTE INT,
	PADECIMIENTO_ACTUAL VARCHAR(2000),
	EXAMEN_FISICO VARCHAR(2000),
	IMPRESION_DIAGNOSTICA VARCHAR(2000),
	PLAN_TRATAMIENTO VARCHAR(2000)
);
GO


--LLAVES FORANEAS

--TABLA USUARIO
--REFERENCIA A LA TABLA ROL
ALTER TABLE USUARIO 
ADD CONSTRAINT FK_USUARIO_ROL
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA CITA
--REFERENCIA A LA TABLA USUARIO
ALTER TABLE CITA 
ADD CONSTRAINT FK_CITA_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A LA TABLA PACIENTE
ALTER TABLE CITA 
ADD CONSTRAINT FK_CITA_PACIENTE
FOREIGN KEY (CEDULA_PACIENTE) REFERENCES PACIENTE(CEDULA_PACIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA PACIENTE
--REFERENCIA A LA TABLA SEXO
ALTER TABLE PACIENTE 
ADD CONSTRAINT FK_PACIENTE_SEXO
FOREIGN KEY(ID_SEXO) REFERENCES SEXO(ID_SEXO)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA OCUPACION
ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_OCUPACION
FOREIGN KEY (ID_OCUPACION) REFERENCES OCUPACION(ID_OCUPACION)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA DIRECCION
ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_DIRECCION
FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA DIRECCION
--REFERENCIA A TABLA PROVINCIA
ALTER TABLE DIRECCION
ADD CONSTRAINT FK_DIRECCION_PROVINCIA
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
ON DELETE CASCADE
ON UPDATE CASCADE;

--REFERENCIA A TABLA CANTON
ALTER TABLE DIRECCION
ADD CONSTRAINT FK_DIRECCION_CANTON
FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON)
ON DELETE CASCADE
ON UPDATE CASCADE;


--TABLA CANTÓN
--REFERENCIA A LA TABLA PROVINCIA
ALTER TABLE CANTON
ADD CONSTRAINT FK_CANTON_PROVINCIA
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

--TABLA EXPEDIENTE
--REFERENCIA A TABLA PACIENTE
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_PACIENTE
FOREIGN KEY (CEDULA_PACIENTE) REFERENCES PACIENTE(CEDULA_PACIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;


--REFERENCIA A TABLA ANTECEDENTES
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_ANTECEDENTES
FOREIGN KEY (ID_ANTECEDENTES) REFERENCES ANTECEDENTES (ID_ANTECEDENTES)
ON DELETE CASCADE
ON UPDATE CASCADE;

--TABLA BITACORA
--REFERENCIA A TABLA BITACORA
ALTER TABLE BITACORA
ADD CONSTRAINT FK_BITACORA_EXPEDIENTE
FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE)
ON DELETE CASCADE
ON UPDATE CASCADE;
GO

--INSERTAR DATOS
-- Llenar tabla PROVINCIA
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA)
VALUES ('San José'),
       ('Alajuela'),
       ('Cartago'),
       ('Heredia'),
       ('Guanacaste'),
       ('Puntarenas'),
       ('Limón');

-- Llenar tabla CANTON
INSERT INTO CANTON (ID_PROVINCIA, NOMBRE_PROVINCIA)
VALUES (1, 'San José'),
       (1, 'Escazú'),
       (1, 'Desamparados'),
       (1, 'Puriscal'),
       (1, 'Tarrazú'),
       (1, 'Aserrí'),
       (1, 'Mora'),
       (1, 'Goicoechea'),
       (1, 'Santa Ana'),
       (1, 'Alajuelita'),
       (2, 'Alajuela'),
       (2, 'San Ramón'),
       (2, 'Grecia'),
       (2, 'San Mateo'),
       (2, 'Atenas'),
       (2, 'Naranjo'),
       (2, 'Palmares'),
       (2, 'Poás'),
       (2, 'Orotina'),
       (2, 'Sarchí'),
       (3, 'Cartago'),
       (3, 'Paraíso'),
       (3, 'La Unión'),
       (3, 'Jiménez'),
       (3, 'Turrialba'),
       (3, 'Alvarado'),
       (3, 'Oreamuno'),
       (3, 'El Guarco'),
       (4, 'Heredia'),
       (4, 'Barva'),
       (4, 'Santo Domingo'),
       (4, 'Santa Bárbara'),
       (4, 'San Rafael'),
       (4, 'San Isidro'),
       (4, 'Belén'),
       (4, 'Flores'),
       (4, 'San Pablo'),
       (4, 'Sarapiquí'),
       (5, 'Liberia'),
       (5, 'Nicoya'),
       (5, 'Santa Cruz'),
       (5, 'Bagaces'),
       (5, 'Carrillo'),
       (5, 'Cañas'),
       (5, 'Abangares'),
       (5, 'Tilarán'),
       (5, 'Nandayure'),
       (5, 'La Cruz'),
       (5, 'Hojancha'),
       (6, 'Puntarenas'),
       (6, 'Esparza'),
       (6, 'Buenos Aires'),
       (6, 'Montes de Oro'),
       (6, 'Osa'),
       (6, 'Quepos'),
       (6, 'Golfito'),
       (6, 'Coto Brus'),
       (6, 'Parrita'),
       (6, 'Corredores'),
       (7, 'Limón'),
       (7, 'Pococí'),
       (7, 'Siquirres'),
       (7, 'Talamanca'),
       (7, 'Matina'),
       (7, 'Guácimo');

--LLENAR TABLA SEXO
INSERT INTO CLINICA_REUMATOLOGIA.DBO.SEXO VALUES
	('Hombre'),
	('Mujer');

--TABLA OCUPACIÓN
INSERT INTO CLINICA_REUMATOLOGIA.DBO.OCUPACION VALUES
	('Empleado'),
	('Desempleado'),
	('Estudiante'),
	('Rentista'),
	('Pensionado');
GO

--PROCEDIMIENTOS ALMACENADOS
--TABLA PACIENTE

--INSERTAR PACIENTE
CREATE OR ALTER PROCEDURE DBO.SP_INSERTAR_PACIENTE(
	@CEDULA_PACIENTE VARCHAR(50),
	@NOMBRE VARCHAR(100),
	@PRIMER_APELLIDO VARCHAR(100),
	@SEGUNDO_APELLIDO VARCHAR(100),
	@EDAD INT,
	@ID_SEXO INT,
	@ID_OCUPACION INT,
	@ID_DIRECCION INT,
	@FECHA_NACIMIENTO DATE
) AS
BEGIN
	INSERT INTO CLINICA_REUMATOLOGIA.DBO.PACIENTE VALUES(
		@CEDULA_PACIENTE,
		@NOMBRE,
		@PRIMER_APELLIDO,
		@SEGUNDO_APELLIDO,
		@EDAD,
		@ID_SEXO,
		@ID_OCUPACION,
		@ID_DIRECCION,
		@FECHA_NACIMIENTO);
END;
GO

--OBTENER PACIENTE
CREATE OR ALTER PROCEDURE DBO.SP_OBTENER_PACIENTE(
	@CEDULA_PACIENTE VARCHAR(50)
) AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.PACIENTE
	WHERE CEDULA_PACIENTE = @CEDULA_PACIENTE;
END;
GO

--LISTAR PACIENTES
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_PACIENTES AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.PACIENTE;
END;
GO

--EDITAR PACIENTE
CREATE OR ALTER PROCEDURE DBO.SP_EDITAR_PACIENTE(
	@CEDULA_PACIENTE VARCHAR(50),
	@NOMBRE VARCHAR(100),
	@PRIMER_APELLIDO VARCHAR(100),
	@SEGUNDO_APELLIDO VARCHAR(100),
	@EDAD INT,
	@ID_SEXO INT,
	@ID_OCUPACION INT,
	@ID_DIRECCION INT,
	@FECHA_NACIMIENTO DATE	
) AS
BEGIN
	UPDATE CLINICA_REUMATOLOGIA.DBO.PACIENTE SET
	CEDULA_PACIENTE = @CEDULA_PACIENTE,
	NOMBRE = @NOMBRE,
	PRIMER_APELLIDO = @PRIMER_APELLIDO,
	SEGUNDO_APELLIDO = @SEGUNDO_APELLIDO,
	EDAD = @EDAD,
	ID_SEXO = @ID_SEXO,
	ID_OCUPACION = @ID_OCUPACION,
	ID_DIRECCION = @ID_DIRECCION,
	FECHA_NACIMIENTO = @FECHA_NACIMIENTO
	WHERE CEDULA_PACIENTE = @CEDULA_PACIENTE;
END;
GO

--ELIMINAR PACIENTE
CREATE OR ALTER PROCEDURE DBO.SP_ELIMINAR_PACIENTE(
	@CEDULA_PACIENTE VARCHAR(50)
) AS
BEGIN
	DELETE FROM CLINICA_REUMATOLOGIA.DBO.PACIENTE
	WHERE CEDULA_PACIENTE = @CEDULA_PACIENTE;
END;
GO

--TABLA EXPEDIENTE
--INSERTAR EXPEDIENTE
CREATE OR ALTER PROCEDURE DBO.SP_INSERTAR_EXPEDIENTE(
	@CEDULA_PACIENTE VARCHAR(50),
	@ID_ANTECEDENTES INT
) AS
BEGIN
	INSERT INTO CLINICA_REUMATOLOGIA.DBO.EXPEDIENTE
	VALUES (@CEDULA_PACIENTE,
			@ID_ANTECEDENTES);
END;
GO

--OBTENER EXPEDIENTE
CREATE OR ALTER PROCEDURE DBO.SP_OBTENER_EXPEDIENTE(
	@ID_EXPEDIENTE INT
) AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.EXPEDIENTE
	WHERE ID_EXPEDIENTE = @ID_EXPEDIENTE;
END;
GO

--LISTAR EXPEDIENTES
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_EXPEDIENTES AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.EXPEDIENTE;
END;
GO 

--EDITAR EXPEDIENTE
CREATE OR ALTER PROCEDURE DBO.SP_EDITAR_EXPEDIENTE(
	@ID_EXPEDIENTE INT,
	@CEDULA_PACIENTE VARCHAR(50),
	@ID_ANTECEDENTES INT
) AS
BEGIN
	UPDATE CLINICA_REUMATOLOGIA.DBO.EXPEDIENTE SET
	CEDULA_PACIENTE = @CEDULA_PACIENTE,
	ID_ANTECEDENTES = @ID_ANTECEDENTES
	WHERE ID_EXPEDIENTE = @ID_EXPEDIENTE;
END;
GO

--ELIMINAR EXPEDIENTE
CREATE OR ALTER PROCEDURE DBO.SP_ELIMINAR_EXPEDIENTE(
	@ID_EXPEDIENTE INT
) AS
BEGIN
	DELETE FROM CLINICA_REUMATOLOGIA.DBO.EXPEDIENTE
	WHERE ID_EXPEDIENTE = @ID_EXPEDIENTE;
END;

GO
--TABLA ANTECEDENTES
--INSERTAR ANTECEDENTES
CREATE OR ALTER PROCEDURE DBO.SP_INSERTAR_ANTECEDENTE(
	@AGO VARCHAR(2000),
	@APnoP VARCHAR(2000),
	@APP VARCHAR(2000),
	@AHF VARCHAR(2000),
	@AQTx VARCHAR(2000)	
) AS
BEGIN
	INSERT INTO CLINICA_REUMATOLOGIA.DBO.ANTECEDENTES
	VALUES (@AGO, @APnoP,@APP,@AHF, @AQTx);
END;
GO

--OBTENER ANTECEDENTES
CREATE OR ALTER PROCEDURE DBO.SP_OBTENER_ANTECEDENTES(
	@ID_ANTECEDENTES INT
) AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.ANTECEDENTES
	WHERE ID_ANTECEDENTES = @ID_ANTECEDENTES;
END;
GO

--LISTAR ANTECEDENTES
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_ANTECEDENTES AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.ANTECEDENTES;
END;
GO

--EDITAR EXPEDIENTE
CREATE OR ALTER PROCEDURE DBO.SP_EDITAR_ANTECEDENTE(
	@ID_ANTECEDENTES INT,
	@AGO VARCHAR(2000),
	@APnoP VARCHAR(2000),
	@APP VARCHAR(2000),
	@AHF VARCHAR(2000),
	@AQTx VARCHAR(2000)	
) AS
BEGIN
	UPDATE CLINICA_REUMATOLOGIA.DBO.ANTECEDENTES SET
	AGO=@AGO, 
	APNOp=@APnoP,
	APP=@APP,
	AHF=@AHF,
	AQTx=@AQTx
	where ID_ANTECEDENTES = @ID_ANTECEDENTES;
END;
GO

--ELIMINAR ANTECEDENTES
CREATE OR ALTER PROCEDURE DBO.SP_ELIMINAR_ANTECEDENTE(
	@ID_ANTECEDENTES INT
) AS
BEGIN
	DELETE FROM CLINICA_REUMATOLOGIA.DBO.ANTECEDENTES
	WHERE ID_ANTECEDENTES = @ID_ANTECEDENTES;
END;
GO

--TABLA DIRECCION
CREATE OR ALTER PROCEDURE DBO.SP_INSERTAR_DIRECCION(
	@PROVINCIA INT,
	@CANTON INT, 
	@DIRECCION VARCHAR(200)
) AS
BEGIN
 INSERT INTO CLINICA_REUMATOLOGIA.DBO.DIRECCION
 VALUES (@PROVINCIA, @CANTON, @DIRECCION)
END;
GO

--TABLA OCUPACION
--OBTENER OCUPACIONES
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_OCUPACION AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.OCUPACION;
END;
GO

--TABLA SEXO
--OBTENER SEXOS
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_SEXO AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.SEXO;
END;
GO

--TABLA PROVINCIA
--OBTENER PROVINCIAS
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_PROVINCIA AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.PROVINCIA;
END;
GO

--TABLA CANTÓN
--OBTENER CANTONES
CREATE OR ALTER PROCEDURE DBO.SP_LISTAR_CANTON AS
BEGIN
	SELECT * FROM CLINICA_REUMATOLOGIA.DBO.CANTON;
END;
GO












